### ISSUE TITLE
How to download the images in that dataset

### ISSUE THREAD

**Issue by jingweimo** [kehuantiantang/A-DNN-based-Semantic-Segmentation-for-Detecting-Weed-and-Crop#1]
I am curious about where the original dataset are stored. Each file is .npy file is organized in the format as follows: 
```
version https://git-lfs.github.com/spec/v1
oid sha256:6692f38904c1ae21cd3d3e6e378538c07fda86fe97ee01d8664bb95fc20cd1de
size 8889498
```
I created a stackoverflow post: https://stackoverflow.com/questions/65603062/how-to-download-git-lfs-files-using-the-oid-sha256-information. You may provide some information about how to use the data in your github repo.

**Comment by kehuantiantang** [comment]
Think you so much for your interesting. I think it maybe the quato problem of my account,  I will refresh the download link those days.  Thank you so much.

**Comment by kehuantiantang** [comment]
> I am curious about where the original dataset are stored. Each file is .npy file is organized in the format as follows:
> 
> ```
> version https://git-lfs.github.com/spec/v1
> oid sha256:6692f38904c1ae21cd3d3e6e378538c07fda86fe97ee01d8664bb95fc20cd1de
> size 8889498
> ```
> 
> I created a stackoverflow post: https://stackoverflow.com/questions/65603062/how-to-download-git-lfs-files-using-the-oid-sha256-information. You may provide some information about how to use the data in your github repo.

I reload the dataset to google cloud, please refer the [README.md](https://github.com/kehuantiantang/A-DNN-based-Semantic-Segmentation-for-Detecting-Weed-and-Crop/blob/master/README.md) to get the download link.

**Comment by jingweimo** [comment]
Thank you!
